### ISSUE TITLE
Problems with fillable PDFs?

### ISSUE THREAD

**Issue by NoahCardoza** [vizicsaba89/pdf-signer#16]
It seems that this lib has problems working with fillable PDFs:
```
(node:24914) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at getXref (/Users/vulcan/tmp/ns/node_modules/pdf-signer/dist/pdf/node-signpdf/read-pdf.js:84:34)
    at getFullXrefTable (/Users/vulcan/tmp/ns/node_modules/pdf-signer/dist/pdf/node-signpdf/read-pdf.js:63:25)
    at readRefTable (/Users/vulcan/tmp/ns/node_modules/pdf-signer/dist/pdf/node-signpdf/read-pdf.js:45:25)
    at Object.readPdf [as default] (/Users/vulcan/tmp/ns/node_modules/pdf-signer/dist/pdf/node-signpdf/read-pdf.js:23:20)
    at /Users/vulcan/tmp/ns/node_modules/pdf-signer/dist/pdf/node-signpdf/plain-add-placeholder.js:61:46
    at step (/Users/vulcan/tmp/ns/node_modules/pdf-signer/dist/pdf/node-signpdf/plain-add-placeholder.js:33:23)
    at Object.next (/Users/vulcan/tmp/ns/node_modules/pdf-signer/dist/pdf/node-signpdf/plain-add-placeholder.js:14:53)
    at /Users/vulcan/tmp/ns/node_modules/pdf-signer/dist/pdf/node-signpdf/plain-add-placeholder.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/vulcan/tmp/ns/node_modules/pdf-signer/dist/pdf/node-signpdf/plain-add-placeholder.js:4:12)
```

**Comment by NoahCardoza** [comment]
I just created an [example repo](https://github.com/NoahCardoza/node-signpdf-bug) so you can easily see what I'm working with!

**Comment by saargospa** [comment]
Is this fixed in any branch ? Actually master doesn't work on PDF > v1.3 , it brokes

**Comment by pankucsi** [comment]
No it is not fixed and it is not a bug. Unfortunately we are not compatible with the new pdf version. You can solve this if you are downgrade the PDF's version.

You can read more about the problem in this issue if you are interested in it: [https://github.com/vizicsaba89/pdf-signer/issues/17](url)

**Comment by dabi07ravi** [comment]
how to show the green tick validation through this library
